services:
  db:
    image: postgres:16
    restart: always
    container_name: integration-tests-enrol
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: courses
      POSTGRES_PASSWORD: courses
      POSTGRES_DB: courses